---
title: "Hill_postulae"
author: "Michael Roswell, Mark Genung, Tina Harrison"
date: "2/14/2022"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Some of what makes one $\ell$ value more predictive of function than another is
about biology, other parts are about math. This is a live document to record
some quantitative relationships (both formal and informal) about Hill diversity
that may lead to clearer interpretations of empirical findings.

## Hill number definition

We define Hill diversity $D$ as the mean species rarity in the assemblage

$$D=\left( \sum_{i=1}^{S}p_{i}(r_{i})^{\ell} \right)^{1/\ell} \tag{1}$$

where $D$ is diversity or mean rarity, $p_{i}$ is the relative abundance of
species $i$, $r_{i}$ is the rarity of species $i$ (defined as the reciprocal of
$p_{i}$), $S$ is the total species richness, and $\ell$ is the scaling exponent
that determines the type of mean computed [@Roswell2021]. 

Hill diversity is more commonly written as

$$D=\left( \sum_{i=1}^{S}p_{i}^{q} \right)^{1/1-q} \tag{2}$$
When $\ell = 0$ ($q = 1$), these equations are defined by their limit.

Equations 1 and 2 are equivalent when $\ell = 1-q$.

## Ranges of Hill numbers (assuming perfect observation)

For a given combination of $S$, $N$ (i.e. number of individuals), and $\ell$, 
there is a range of values that $D$ can possibly take. When $\ell$ is large, 
this range is also large, and when it is a large negative number, the range is 
much smaller, when $\ell = 1$ this range is at its minimum, $D=S$, for any $N$,
distribution of relative abundance.

For $\ell \geq 1$, the minimum value $D$ can take is $S$ (maximum evenness). As
$\ell \rightarrow \infty$, the maximum value of $D$ grows to the maximum species
rarity, i.e. $N$. When $1 \leq \ell < \infty$, $D$ reaches its maximum with
maximum dominance, but as $\ell \rightarrow \infty$ the maximum rarity drives
$D$ regardless of the shape of the species abundance distribution.

For $\ell <1$, the *maximum* value $D$ can take is $S$ (maximum evenness). As
$\ell \rightarrow -\infty$, the minimum value of $D$ shrinks to the minimum
species rarity, i.e. something nearing $1$ when $N >> S$ (maximum dominance).

## D-flipping

For a given $S$, $N$, the spearman rank correlation between the Hill diversity
of a set of assemblages when $\ell = \infty$ and when $\ell = -\infty$ is $-1$.
More simply, the even assemblage has maximum diversity for $\ell<1$ and minimum
diversity when $\ell>1$.

## interpretations

When $\ell \rightarrow \infty$, $D$ conveys information primarily about
*abundance*

When $\ell \rightarrow -\infty$, $D$ conveys information primarily about
*dominance* (but not really evenness, which is complicated)

When the predictive ability of $D$ is maximized when $\ell \neq (-\infty, 1,
\infty)$ it is hard to say what aspects of the SAD are most salient.





